// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mgmt_svc.proto

#ifndef PROTOBUF_mgmt_5fsvc_2eproto__INCLUDED
#define PROTOBUF_mgmt_5fsvc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace diststore {
class GetMembershipRequest;
class GetMembershipRequestDefaultTypeInternal;
extern GetMembershipRequestDefaultTypeInternal _GetMembershipRequest_default_instance_;
class GetMembershipResponse;
class GetMembershipResponseDefaultTypeInternal;
extern GetMembershipResponseDefaultTypeInternal _GetMembershipResponse_default_instance_;
}  // namespace diststore

namespace diststore {

namespace protobuf_mgmt_5fsvc_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_mgmt_5fsvc_2eproto

// ===================================================================

class GetMembershipRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:diststore.GetMembershipRequest) */ {
 public:
  GetMembershipRequest();
  virtual ~GetMembershipRequest();

  GetMembershipRequest(const GetMembershipRequest& from);

  inline GetMembershipRequest& operator=(const GetMembershipRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetMembershipRequest& default_instance();

  static inline const GetMembershipRequest* internal_default_instance() {
    return reinterpret_cast<const GetMembershipRequest*>(
               &_GetMembershipRequest_default_instance_);
  }

  void Swap(GetMembershipRequest* other);

  // implements Message ----------------------------------------------

  inline GetMembershipRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  GetMembershipRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetMembershipRequest& from);
  void MergeFrom(const GetMembershipRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetMembershipRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:diststore.GetMembershipRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct  protobuf_mgmt_5fsvc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GetMembershipResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:diststore.GetMembershipResponse) */ {
 public:
  GetMembershipResponse();
  virtual ~GetMembershipResponse();

  GetMembershipResponse(const GetMembershipResponse& from);

  inline GetMembershipResponse& operator=(const GetMembershipResponse& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GetMembershipResponse& default_instance();

  static inline const GetMembershipResponse* internal_default_instance() {
    return reinterpret_cast<const GetMembershipResponse*>(
               &_GetMembershipResponse_default_instance_);
  }

  void Swap(GetMembershipResponse* other);

  // implements Message ----------------------------------------------

  inline GetMembershipResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  GetMembershipResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetMembershipResponse& from);
  void MergeFrom(const GetMembershipResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetMembershipResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string member1 = 1;
  void clear_member1();
  static const int kMember1FieldNumber = 1;
  const ::std::string& member1() const;
  void set_member1(const ::std::string& value);
  #if LANG_CXX11
  void set_member1(::std::string&& value);
  #endif
  void set_member1(const char* value);
  void set_member1(const char* value, size_t size);
  ::std::string* mutable_member1();
  ::std::string* release_member1();
  void set_allocated_member1(::std::string* member1);

  // string member2 = 2;
  void clear_member2();
  static const int kMember2FieldNumber = 2;
  const ::std::string& member2() const;
  void set_member2(const ::std::string& value);
  #if LANG_CXX11
  void set_member2(::std::string&& value);
  #endif
  void set_member2(const char* value);
  void set_member2(const char* value, size_t size);
  ::std::string* mutable_member2();
  ::std::string* release_member2();
  void set_allocated_member2(::std::string* member2);

  // string member3 = 3;
  void clear_member3();
  static const int kMember3FieldNumber = 3;
  const ::std::string& member3() const;
  void set_member3(const ::std::string& value);
  #if LANG_CXX11
  void set_member3(::std::string&& value);
  #endif
  void set_member3(const char* value);
  void set_member3(const char* value, size_t size);
  ::std::string* mutable_member3();
  ::std::string* release_member3();
  void set_allocated_member3(::std::string* member3);

  // @@protoc_insertion_point(class_scope:diststore.GetMembershipResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr member1_;
  ::google::protobuf::internal::ArenaStringPtr member2_;
  ::google::protobuf::internal::ArenaStringPtr member3_;
  mutable int _cached_size_;
  friend struct  protobuf_mgmt_5fsvc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// GetMembershipRequest

// -------------------------------------------------------------------

// GetMembershipResponse

// string member1 = 1;
inline void GetMembershipResponse::clear_member1() {
  member1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetMembershipResponse::member1() const {
  // @@protoc_insertion_point(field_get:diststore.GetMembershipResponse.member1)
  return member1_.GetNoArena();
}
inline void GetMembershipResponse::set_member1(const ::std::string& value) {
  
  member1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:diststore.GetMembershipResponse.member1)
}
#if LANG_CXX11
inline void GetMembershipResponse::set_member1(::std::string&& value) {
  
  member1_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:diststore.GetMembershipResponse.member1)
}
#endif
inline void GetMembershipResponse::set_member1(const char* value) {
  
  member1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:diststore.GetMembershipResponse.member1)
}
inline void GetMembershipResponse::set_member1(const char* value, size_t size) {
  
  member1_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:diststore.GetMembershipResponse.member1)
}
inline ::std::string* GetMembershipResponse::mutable_member1() {
  
  // @@protoc_insertion_point(field_mutable:diststore.GetMembershipResponse.member1)
  return member1_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetMembershipResponse::release_member1() {
  // @@protoc_insertion_point(field_release:diststore.GetMembershipResponse.member1)
  
  return member1_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetMembershipResponse::set_allocated_member1(::std::string* member1) {
  if (member1 != NULL) {
    
  } else {
    
  }
  member1_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), member1);
  // @@protoc_insertion_point(field_set_allocated:diststore.GetMembershipResponse.member1)
}

// string member2 = 2;
inline void GetMembershipResponse::clear_member2() {
  member2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetMembershipResponse::member2() const {
  // @@protoc_insertion_point(field_get:diststore.GetMembershipResponse.member2)
  return member2_.GetNoArena();
}
inline void GetMembershipResponse::set_member2(const ::std::string& value) {
  
  member2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:diststore.GetMembershipResponse.member2)
}
#if LANG_CXX11
inline void GetMembershipResponse::set_member2(::std::string&& value) {
  
  member2_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:diststore.GetMembershipResponse.member2)
}
#endif
inline void GetMembershipResponse::set_member2(const char* value) {
  
  member2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:diststore.GetMembershipResponse.member2)
}
inline void GetMembershipResponse::set_member2(const char* value, size_t size) {
  
  member2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:diststore.GetMembershipResponse.member2)
}
inline ::std::string* GetMembershipResponse::mutable_member2() {
  
  // @@protoc_insertion_point(field_mutable:diststore.GetMembershipResponse.member2)
  return member2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetMembershipResponse::release_member2() {
  // @@protoc_insertion_point(field_release:diststore.GetMembershipResponse.member2)
  
  return member2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetMembershipResponse::set_allocated_member2(::std::string* member2) {
  if (member2 != NULL) {
    
  } else {
    
  }
  member2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), member2);
  // @@protoc_insertion_point(field_set_allocated:diststore.GetMembershipResponse.member2)
}

// string member3 = 3;
inline void GetMembershipResponse::clear_member3() {
  member3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GetMembershipResponse::member3() const {
  // @@protoc_insertion_point(field_get:diststore.GetMembershipResponse.member3)
  return member3_.GetNoArena();
}
inline void GetMembershipResponse::set_member3(const ::std::string& value) {
  
  member3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:diststore.GetMembershipResponse.member3)
}
#if LANG_CXX11
inline void GetMembershipResponse::set_member3(::std::string&& value) {
  
  member3_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:diststore.GetMembershipResponse.member3)
}
#endif
inline void GetMembershipResponse::set_member3(const char* value) {
  
  member3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:diststore.GetMembershipResponse.member3)
}
inline void GetMembershipResponse::set_member3(const char* value, size_t size) {
  
  member3_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:diststore.GetMembershipResponse.member3)
}
inline ::std::string* GetMembershipResponse::mutable_member3() {
  
  // @@protoc_insertion_point(field_mutable:diststore.GetMembershipResponse.member3)
  return member3_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GetMembershipResponse::release_member3() {
  // @@protoc_insertion_point(field_release:diststore.GetMembershipResponse.member3)
  
  return member3_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GetMembershipResponse::set_allocated_member3(::std::string* member3) {
  if (member3 != NULL) {
    
  } else {
    
  }
  member3_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), member3);
  // @@protoc_insertion_point(field_set_allocated:diststore.GetMembershipResponse.member3)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace diststore

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_mgmt_5fsvc_2eproto__INCLUDED
