// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: mgmt_svc.proto
#ifndef GRPC_mgmt_5fsvc_2eproto__INCLUDED
#define GRPC_mgmt_5fsvc_2eproto__INCLUDED

#include "mgmt_svc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace diststore {

class MgmtService final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetMembership(::grpc::ClientContext* context, const ::diststore::GetMembershipRequest& request, ::diststore::GetMembershipResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::diststore::GetMembershipResponse>> AsyncGetMembership(::grpc::ClientContext* context, const ::diststore::GetMembershipRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::diststore::GetMembershipResponse>>(AsyncGetMembershipRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::diststore::GetMembershipResponse>* AsyncGetMembershipRaw(::grpc::ClientContext* context, const ::diststore::GetMembershipRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetMembership(::grpc::ClientContext* context, const ::diststore::GetMembershipRequest& request, ::diststore::GetMembershipResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::diststore::GetMembershipResponse>> AsyncGetMembership(::grpc::ClientContext* context, const ::diststore::GetMembershipRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::diststore::GetMembershipResponse>>(AsyncGetMembershipRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::diststore::GetMembershipResponse>* AsyncGetMembershipRaw(::grpc::ClientContext* context, const ::diststore::GetMembershipRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_GetMembership_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetMembership(::grpc::ServerContext* context, const ::diststore::GetMembershipRequest* request, ::diststore::GetMembershipResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMembership : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetMembership() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetMembership() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMembership(::grpc::ServerContext* context, const ::diststore::GetMembershipRequest* request, ::diststore::GetMembershipResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMembership(::grpc::ServerContext* context, ::diststore::GetMembershipRequest* request, ::grpc::ServerAsyncResponseWriter< ::diststore::GetMembershipResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetMembership<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetMembership : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetMembership() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetMembership() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMembership(::grpc::ServerContext* context, const ::diststore::GetMembershipRequest* request, ::diststore::GetMembershipResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMembership : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetMembership() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::diststore::GetMembershipRequest, ::diststore::GetMembershipResponse>(std::bind(&WithStreamedUnaryMethod_GetMembership<BaseClass>::StreamedGetMembership, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetMembership() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMembership(::grpc::ServerContext* context, const ::diststore::GetMembershipRequest* request, ::diststore::GetMembershipResponse* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMembership(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::diststore::GetMembershipRequest,::diststore::GetMembershipResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetMembership<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetMembership<Service > StreamedService;
};

}  // namespace diststore


#endif  // GRPC_mgmt_5fsvc_2eproto__INCLUDED
